# Generated by Django 5.0 on 2023-12-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_alter_reading_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='data_add',
            field=models.BooleanField(default=False),
        ),
    ]
