# Generated by Django 5.0 on 2023-12-16 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_reading_data_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='data_add',
            new_name='paid',
        ),
    ]
